version: '3.4'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ChatSystem
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db:/var/run/mysqld

  redis:
    image: redis:5-alpine
    command: redis-server
    restart: always
    ports:
      - 6379:6379
    volumes:
      - 'redis:/data'
  
  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: bundle exec sidekiq
    restart: always
    volumes:
      - '.:/app'
      - '/app/tmp'
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_USER: root
      DB_NAME: ChatSystem
      DB_PASSWORD: root
      DB_HOST: db
    links:
      - db
      - redis

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
      - sidekiq
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_SOCKET: /var/run/mysqld/mysqld.so
      RAILS_ENV: development
      DB_NAME: ChatSystem
      DB_HOST: db
      DB_PORT: 3306
      DB_POOL: 5
      REDIS_URL: redis://redis:6379/0
    links: 
      - db
      - redis
      - sidekiq

volumes:
  db:
  redis:
  