version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    volumes:
      - .:/app
      - /usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ChatSystem
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db:/var/run/mysqld

  redis:
    image: redis:5-alpine
    command: redis-server
    restart: always
    ports:
      - 6379:6379
    volumes:
      - 'redis:/data'
  
  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    entrypoint: []
    command: bundle exec sidekiq
    restart: always
    volumes:
      - '.:/app'
      - '/app/tmp'
    environment:
      DB_USER: root
      DB_NAME: ChatSystem
      DB_PASSWORD: root
      DB_HOST: db
      REDIS_URL: redis://redis:6379/0
      ELASTICSEARCH_URL: http://elasticsearch:9200
    links:
      - db
      - redis
      - elasticsearch

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
      - sidekiq
      - elasticsearch
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_SOCKET: /var/run/mysqld/mysqld.so
      RAILS_ENV: development
      DB_NAME: ChatSystem
      DB_HOST: db
      DB_PORT: 3306
      DB_POOL: 5
      REDIS_URL: redis://redis:6379/0
      ELASTICSEARCH_URL: http://elasticsearch:9200
    links: 
      - db
      - redis
      - sidekiq
      - elasticsearch

volumes:
  db:
  redis:
  