version: '3.4'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ChatSystem
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db:/var/run/mysqld

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - gem_cache:/usr/local/bundle/gems
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_SOCKET: /var/run/mysqld/mysqld.so
      RAILS_ENV: development
      DB_NAME: ChatSystem
      DB_HOST: db
      DB_PORT: 3306
      DB_POOL: 5
    links: 
      - db

volumes:
  db:
  gem_cache:
  node_modules:
  